-- wgs@test

CREATE TABLE IF NOT EXISTS `source_file_tar`(
    `id` INT(10) unsigned NOT NULL AUTO_INCREMENT,
    `user_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
    `upload_path` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '上传路径',
    `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '任务状态 0-解析中，1-解析完成，-1=解析失败',
    `message` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '错误信息',
    `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `updated_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8 COMMENT='文件包列表';

